seed: 2026
model: adman
device: cuda
gpu: '0'
data:
  pet_root: source domain folder
  pet_domain_high: source domain subfolder
  pet_domain_low: simulated subfolder
  hr_domain_high: source domain folder
  hr_domain_low: simulated folder
  target_root: target domain folder
  target_domain: target domain subfolder
training:
  batch_size: 16
  iteration: 20000
  lr:
    - 0.001
    - 0.01
  optimizer:
    name: sgd
    momentum: 0.9
    weight_decay: 0.0005
  class_num: 2
  log_interval: 10
  eval_interval: 50
  patience: 100
checkpoint:
  pretrained:
    enabled: false
    model_path: null
  output_dir: output folder
  best_name: best.pth
  topk: 200
evaluation:
  test_root: evaluation folder
  test_domain: evaluation subfolder
  output_dir: output folder
